version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:6.8.7
    environment:
      cluster.name: elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: kibana:6.8.7
    environment:
      ELASTICSEARCH_URL: http://192.168.58.198:9200
    ports:
      - 5601:5601